### PR TITLE
feat: added esm and cjs export

### PR DESCRIPTION
**Pull request by prisis**
| 🚥 Resolves ISSUE_ID |
| :------------------- |

## 🧰 Changes

Added support for cjs and esm

## 🧬 QA & Testing

Check the generated files in the dist folder

### CODE REVIEW

**Comment by prisis** [comment]
2 Questions, are you fine if i update the style-formatting and try to get rid of the lodash dep?

**Review by erunion — APPROVED** [review]
amazing

**Comment by erunion** [comment]
@prisis We use Lodash in there for the dot.notation support that `get` and `set` offer so I'm a little weary of moving to something custom and not as tested as that but if you've got something that'll work there by all means I'd happy accept a PR.

**Comment by erunion** [comment]
Also we'd love to send you some ReadMe swag for this work you've been doing. You can email either me or @kanadgupta at jon AT readme DOT io or kanad AT readme DOT io and we'll hook you up. Thanks again for all this, we've been dreading ESM for a while now.

**Pull request merged**
